### ISSUE TITLE
Add tests for each supported dbms

### ISSUE THREAD

**Issue by ablack3** [OHDSI/CohortGeneratorModule#24]
What do you think about adding tests for each supported dbms?

**Comment by chrisknoll** [comment]
I think that those should be covered in sqlrender tests.  I agree dbms support should be handled somewhere, but I think CohortGenerator is just one consumer of SqlRender, so SqlRender tests should assert db platform support is handled.

The alternative view on this is for cases where the exact same sql yields different results on different platforms (example, maybe `between` is inclusive on one, exclusive on another).   But I am not sure we're facing those issues (and we should avoid those issues in general that depend on one platform behavior over another).   

So, maybe a small set of test cases would make sense, but ideally I'd like SqlRender be responsible for queries working correctly between dbms.

**Comment by ablack3** [comment]
Well there are cases where errors occur that could not be caught by SqlRender tests. Here is an error I get when running the SOS study on BigQuery. 
<img width="400" alt="image" src="https://github.com/OHDSI/CohortGeneratorModule/assets/10227522/b73886e5-fa8a-49c4-92b7-28918da7feff">

The current CohortGenerator and CohortGeneratorModule tests do not catch this error and it's unclear how this would be caught by SqlRender.

Also SQLRender does not make any guarantees about the correctness of its SQL output so we cannot rely on SQLRender tests to ensure correctness of analytic code. It is only responsible for the translation conditional on the input being correct. If you pass in incorrect OHDSI-SQL (which currently has no formal definition) then the output will be incorrect. There are cases where the input OHDSI-SQL might work on one dbms but not another. 

A recent example of this situation is in the MentalHealthEquity Study I tried to run. The author used quotes around SQL column names which worked fine on some dbms but not on others. SQLRender does not give an error. There is no documentation anywhere stating that quoted column names should not be used. The only way for a study author to discover this is to test on all dbms that will eventually run the study. That test happens during study execution (similar to the strategus example above).

https://github.com/ohdsi-studies/MentalHealthEquity/issues/42

**Comment by chrisknoll** [comment]
I think we agree that testing is necessary, I think my point was the level of testing and the context should be considered.  If it's a question of proper SQL translation, it's a SQLRender concern.  The error you presented above I think came from DatabaseConnector, but could be a way that CohortGenerator (via CohortGeneratorModule) is invoking the DatabaseConnector method.

So, I think the distinction I'm drawing is between unit tests and integration tests.   Example: cohort subgrouping is a function of CohortGenerator (the package, not the module) and so to me it makes sense to store detailed unit tests to ensure corner cases are covered, etc.   And I can imagine having dbms-specific test contexts for that, but when it comes to an integration test between CohortGeneratorModule, I think you just want to ensure that the module is invoking the functions correctly without error, so I don't think we'd want the same level of test-cases in CohortGeneratorModule as you have in CohortGenerator.  Put another way: I'd suggest keeping the tests as close as possible to the location where they can be fixed if it fails.  Otherwise, you'll have these transient issues that cross multiple package boundaries, and it's harder to know who's respoinsible for a fix.  Worse, if the fix is handled somewhere 'down stream', then the fix is only good for the down stream party, not all people who consume from up-stream.

But, long story short, yes, I agree with a test environment (and if we want to be ultra conservative, we need the 10+ platforms that SqlRender supports).   It would probably be helpful to have an env that can be shared between different testing contexts, but that runs some risks of tests colliding between the different repos.   Do we want to have 1 DataBridcks environment per study?  or per git repo?

**Comment by ablack3** [comment]
Yea I agree 100%. All functionality needs to be tested (to the extent possible). Each component should only need to test what it is responsible for. I'd say that if you're component contains OHDSI-SQL then you're responsible for making sure that is correct (by testing it on each dbms). SqlRender won't tell you if your OHDSI-SQL is correct or not.

It seems to me like just having a single database per dbms for testing is currently a bit of a stretch so probably 1 Databricks environment for everyone to share is the best we can do currently. Currently there is no shared OHDSI Databricks (or snowflake) test environment.

**Comment by chrisknoll** [comment]
If setting up the environment is the challenge, maybe we can have dedicated schemas for each context that someone wants to test. I've seen trouble when one shared database (like eunomia) falls short when you need certain data conditions in order to do a complete test for your specific use-case.

**Comment by ablack3** [comment]
> dedicated schemas for each context

Great idea. So what would a module need to test? Maybe run a simple example on each supported dbms?

**Comment by chrisknoll** [comment]
Well, in the case of CohortGeneratorModule, I would say just a simple cohort definition so that we can determine if the correct cohort stats are recorded and the connection was successful.   And yes, on each DBMS (which can be represented as a database ID in the results).   All we want to know is that the spec and the connection settings for each DBMS works.  The more complicated functions like subgrouping should be relegated down to CohortGenerator package.   And CohortGenerator doesn't need to test all different edge cases of CIRCE, that should happen in the cross-platform tests of CIRCE.  You get the idea.   My suggestion about dedicated schemas is that CIRCE, CohortGenerator and CohortGeneratorModule should probably have their own schemas to maintain the test cases that they need because I don't think one schema can contain tests for all contexts, and plus, you mess with a centralized test set, you may impact the expected results in unforseen ways.

**Comment by anthonysena** [comment]
Just noting that OHDSI/CohortGenerator#153 now provides tests for all OHDSI DB Platforms so this will be addressed in the next release of CohortGenerator and this module.
